spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://39.106.133.40:3306/ims?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root
  data:
    mongodb:
      host: 39.106.133.40
      port: 27017
      authentication-database: ims
      username: klk_ims
      password: ims123456
      auth: true
      database: ims
    redis:
      database: 0      # Redis数据库索引（默认为0）
      host: 39.106.133.40  # Redis服务器地址
      port: 6379       # Redis服务器连接端口

server:
  servlet:
    context-path: /ims
  port: 8080

threadpool:
  core-pool-size: 10
  max-pool-size: 20
  queue-capacity: 1000
  keep-alive-seconds: 60

fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    39.106.133.40:22122

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml

logging:
  level:
    org.springframework:
      data: info
      security: info

jwt:
  header: Authorization
  secret: ImsSecret
  expiration: 1800
  tokenHead: "Bearer "

